/* Generated by fontgen. Do not edit. */
/* Regenerate with:
 *   ./tools/fontgen/build/fontgen ./assets/fonts/IBMPlexMono-Regular.ttf 20 0x20-0x7E,0xA3,0x2022,0x20AC,0x221E src/app/render/fonts/ibm_plex_mono_20
 */

/*
 * ---------------------------------------------------------------------------
 * The glyph bitmap data in this file is derived from IBM Plex Mono,
 * Copyright 2017 IBM Corp. (https://github.com/IBM/plex)
 *
 * Licensed under the SIL Open Font License, Version 1.1.
 * The full license text is included with the source font in
 * assets/fonts/OFL.txt and is also available at:
 *     https://scripts.sil.org/OFL
 * ---------------------------------------------------------------------------
 */


#pragma once

#include "font.h"

extern const font_t IBM_PLEX_MONO_20;
